const q=document.querySelector('#q');
const out=document.querySelector('#out');
const status=document.querySelector('#status');
const goalsEl=document.querySelector('#goals');
const summaryEl=document.querySelector('#summary');
const deBtn=document.querySelector('#deBtn');
const enBtn=document.querySelector('#enBtn');
const questDrawer=document.querySelector('#questDrawer');
const questQ=document.querySelector('#questQ');
const questsList=document.querySelector('#questsList');
const questStatus=document.querySelector('#questStatus');
const questSummary=document.querySelector('#questSummary');
const questToggleLabel=document.querySelector('#questToggleLabel');
let items=[],goals=[],quests=[],usingFallback=false,questLoadError=false,questFilter='all';
let lang=localStorage.getItem('arcLang')||'de';
const norm=s=>(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const owned=JSON.parse(localStorage.getItem('arcOwned')||'{}'),active=JSON.parse(localStorage.getItem('arcActiveGoals')||'{}'),questStates=JSON.parse(localStorage.getItem('arcQuestStatus')||'{}');
const T={de:{level:'Stufe',noneGoal:'Noch kein Ausbauziel oder aktive Quest mit Itembedarf.',total:'Gesamt',owned:'vorhanden',missing:'fehlen',value:'Wert',weight:'Gewicht',stack:'Stapel',use:'Beschreibung',recycle:'Recycling',noRecycle:'Keine Recyclingdaten',searchPrompt:'Suchbegriff eingeben',records:'Items geladen',matches:'Treffer',noHit:'Kein Treffer.',free:'FREI – für deine aktiven Ziele aktuell nicht benötigt',fulfilled:'ZIEL ERFÜLLT – du hast genug',keepA:'BEHALTEN – dir fehlen insgesamt noch',keepB:'von',loadError:'Vollständiger Katalog nicht erreichbar – lokaler Basisdatensatz aktiv.',questPlaceholder:'Quest suchen …',questLoading:'Quests werden geladen …',questLoadError:'Questdaten konnten nicht geladen werden.',questsLoaded:'Quests geladen',shown:'angezeigt',objectives:'Ziele',required:'Benötigte Items',rewards:'Belohnungen',granted:'Bereitgestellt',trader:'Auftraggeber',noRequired:'Kein Itembedarf',noRewards:'Keine Itembelohnungen',questReason:'Quest',activeCount:'aktiv',done:'ERLEDIGT',show:'ANZEIGEN',hide:'SCHLIESSEN'},en:{level:'Level',noneGoal:'No upgrade goal or active quest with item requirements.',total:'Total',owned:'owned',missing:'missing',value:'Value',weight:'Weight',stack:'Stack',use:'Description',recycle:'Recycling',noRecycle:'No recycling data',searchPrompt:'Enter a search term',records:'items loaded',matches:'matches',noHit:'No results.',free:'FREE – not currently needed for your active goals',fulfilled:'GOAL MET – you have enough',keepA:'KEEP – you still need',keepB:'of',loadError:'Full catalog unavailable – local base dataset active.',questPlaceholder:'Search quests …',questLoading:'Loading quests …',questLoadError:'Quest data could not be loaded.',questsLoaded:'quests loaded',shown:'shown',objectives:'Objectives',required:'Required items',rewards:'Rewards',granted:'Granted',trader:'Quest giver',noRequired:'No item requirements',noRewards:'No item rewards',questReason:'Quest',activeCount:'active',done:'DONE',show:'SHOW',hide:'CLOSE'}};
function tr(k){return T[lang]?.[k]||T.en[k]||k}function text(obj){return obj?.[lang]||obj?.en||obj?.de||''}function itemName(i){return i?.name?text(i.name):(lang==='de'?(i?.de||i?.en):(i?.en||i?.de))||i?.id||''}function itemDesc(i){return i?.description?text(i.description):(i?.use||'')}function itemWeight(i){return i?.weightKg??i?.weight??null}function itemStack(i){return i?.stackSize??i?.stack??null}function itemById(id){return items.find(x=>x.id===id)}function key(goalId,level){return `${goalId}:${level}`}function questName(x){return text(x?.name)||x?.id?.replaceAll('_',' ')||''}function getQuestState(id){return questStates[id]||'open'}function goalName(g){return (lang==='de'?g.de:g.en)||g.de||g.en||g.id}function formatNum(n){return n===null||n===undefined||n===''?'—':new Intl.NumberFormat(lang==='de'?'de-DE':'en-US',{maximumFractionDigits:2}).format(n)}
function requirementMap(){if(window.RFTPlanning?.requirementMap)return window.RFTPlanning.requirementMap();const map={};const add=(id,quantity,reason)=>{if(!id||!quantity)return;if(!map[id])map[id]={total:0,reasons:[]};map[id].total+=Number(quantity)||0;map[id].reasons.push(reason)};goals.forEach(g=>(g.levels||[]).forEach(l=>{if(active[key(g.id,l.level)])(l.requirements||[]).forEach(r=>add(r.itemId,r.quantity,`${goalName(g)} ${tr('level')} ${l.level}: ${r.quantity}`))}));quests.forEach(x=>{if(getQuestState(x.id)==='active')(x.requiredItemIds||[]).forEach(r=>add(r.itemId,r.quantity,`${tr('questReason')} – ${questName(x)}: ${r.quantity}`))});return map}
function saveOwned(id,val){owned[id]=Math.max(0,Number(val)||0);localStorage.setItem('arcOwned',JSON.stringify(owned));drawSummary();drawItems();window.dispatchEvent(new Event('planning-changed'))}function toggleGoal(k,checked){if(checked)active[k]=true;else delete active[k];localStorage.setItem('arcActiveGoals',JSON.stringify(active));drawSummary();drawItems();window.dispatchEvent(new Event('planning-changed'))}
function drawGoals(){goalsEl.innerHTML=goals.map(g=>`<div class="goalbox"><div class="goalhead">${escapeHtml(goalName(g))}</div><div class="levelrow">${(g.levels||[]).map(l=>`<label class="levelbtn"><input type="checkbox" data-key="${escapeHtml(key(g.id,l.level))}" ${active[key(g.id,l.level)]?'checked':''}>${escapeHtml(tr('level'))} ${escapeHtml(l.level)}</label>`).join('')}</div></div>`).join('');goalsEl.querySelectorAll('input[type=checkbox]').forEach(el=>el.addEventListener('change',e=>toggleGoal(e.target.dataset.key,e.target.checked)))}
function drawSummary(){const entries=Object.entries(requirementMap());if(!entries.length){summaryEl.innerHTML=`<div class="empty">${tr('noneGoal')}</div>`;return}summaryEl.innerHTML=entries.map(([id,r])=>{const i=itemById(id),name=i?itemName(i):id.replaceAll('_',' '),have=owned[id]||0,missing=Math.max(0,r.total-have);return `<div class="sumrow" data-item-id="${escapeHtml(id)}" data-missing="${missing}"><div class="summary-main"><div class="sumname">${escapeHtml(name)}</div><div class="summeta">${tr('total')} ${r.total} · ${tr('owned')} ${have} · ${tr('missing')} ${missing}</div><div class="summeta">${escapeHtml((r.reasons||[]).join(' · '))}</div></div><input class="qty" type="number" min="0" inputmode="numeric" value="${have}" data-id="${escapeHtml(id)}"></div>`}).join('');summaryEl.querySelectorAll('.qty').forEach(el=>el.addEventListener('change',e=>saveOwned(e.target.dataset.id,e.target.value)))}
function goalDecision(i){const req=requirementMap()[i.id];if(!req)return `<div class="need free">${tr('free')}</div>`;const have=owned[i.id]||0,missing=Math.max(0,req.total-have);return missing===0?`<div class="need ok">${tr('fulfilled')}<div class="reasons">${escapeHtml((req.reasons||[]).join(' · '))}</div></div>`:`<div class="need keep">${tr('keepA')} ${missing} ${tr('keepB')} ${req.total}<div class="reasons">${escapeHtml((req.reasons||[]).join(' · '))}</div></div>`}
function recyclingText(i){const rec=i.recyclesInto;if(rec&&typeof rec==='object'&&Object.keys(rec).length)return Object.entries(rec).map(([id,n])=>`${n}× ${itemById(id)?itemName(itemById(id)):id.replaceAll('_',' ')}`).join(' · ');return i.recycle&&i.recycle!=='—'?i.recycle:tr('noRecycle')}
function card(i){return `<article class="card" data-item-id="${escapeHtml(i.id)}"><div class="card-head"><h3>${escapeHtml(itemName(i))}</h3></div><div class="facts"><div class="fact"><span>${tr('value')}</span><b>${formatNum(i.value)}</b></div><div class="fact"><span>${tr('weight')}</span><b>${itemWeight(i)==null?'—':formatNum(itemWeight(i))+' kg'}</b></div><div class="fact"><span>${tr('stack')}</span><b>${formatNum(itemStack(i))}</b></div></div>${itemDesc(i)?`<div class="desc"><b>${tr('use')}:</b> ${escapeHtml(itemDesc(i))}</div>`:''}<div class="recycle"><b>${tr('recycle')}:</b> ${escapeHtml(recyclingText(i))}</div>${goalDecision(i)}</article>`}
function drawItems(){const x=norm(q.value.trim());if(!x){out.innerHTML='';status.textContent=`${items.length} ${tr('records')} · ${tr('searchPrompt')}`;return}const r=items.filter(i=>[itemName(i),i?.name?.de,i?.name?.en,i?.de,i?.en].some(v=>norm(v).includes(x)));status.textContent=`${r.length} ${tr('matches')} · ${items.length} ${tr('records')}`;out.innerHTML=r.length?r.map(card).join(''):`<div class="empty">${tr('noHit')}</div>`}
function questItemsText(arr){return Array.isArray(arr)?arr.map(r=>`${r.quantity}× ${itemById(r.itemId)?itemName(itemById(r.itemId)):r.itemId.replaceAll('_',' ')}`).join(' · '):''}function setQuestState(id,state){questStates[id]=state;localStorage.setItem('arcQuestStatus',JSON.stringify(questStates));drawQuestHeader();drawQuests();drawSummary();drawItems();window.dispatchEvent(new Event('planning-changed'))}
function questCard(x){const st=getQuestState(x.id),objectives=(x.objectives||[]).map(o=>text(o)).filter(Boolean),required=questItemsText(x.requiredItemIds);return `<article class="quest-card quest-${st}"><div class="quest-card-head"><h3>${escapeHtml(questName(x))}</h3><div class="quest-state">${['open','active','done'].map(s=>`<button type="button" data-qid="${escapeHtml(x.id)}" data-state="${s}" class="${st===s?'selected':''}">${s.toUpperCase()}</button>`).join('')}</div></div>${objectives.length?`<div><b>${tr('objectives')}:</b> ${objectives.map(escapeHtml).join(' · ')}</div>`:''}<div><b>${tr('required')}:</b> ${required||tr('noRequired')}</div></article>`}
function drawQuestHeader(){if(!questSummary)return;const n=quests.filter(x=>getQuestState(x.id)==='active').length,done=quests.filter(x=>getQuestState(x.id)==='done').length;questSummary.textContent=quests.length?`${quests.length} ${tr('questsLoaded')} · ${n} ${tr('activeCount')} · ${done} ${tr('done').toLowerCase()}`:(questLoadError?tr('questLoadError'):'');questToggleLabel.textContent=questDrawer.open?tr('hide'):tr('show')}
function drawQuests(){if(!questDrawer.open)return;const needle=norm(questQ.value.trim()),filtered=quests.filter(x=>(questFilter==='all'||getQuestState(x.id)===questFilter)&&(!needle||norm(questName(x)).includes(needle)));questStatus.textContent=`${filtered.length} ${tr('shown')} · ${quests.length} ${tr('questsLoaded')}`;questsList.innerHTML=filtered.length?filtered.map(questCard).join(''):`<div class="empty">${tr('noHit')}</div>`;questsList.querySelectorAll('.quest-state button').forEach(btn=>btn.addEventListener('click',()=>setQuestState(btn.dataset.qid,btn.dataset.state)))}
async function loadQuests(){const r=await fetch('https://api.github.com/repos/RaidTheory/arcraiders-data/contents/quests?ref=main',{cache:'no-store'});if(!r.ok)throw new Error('quest index');const files=await r.json(),loaded=[];for(let i=0;i<files.length;i+=10){const batch=files.slice(i,i+10).filter(f=>f.download_url);const results=await Promise.allSettled(batch.map(f=>fetch(f.download_url,{cache:'no-store'}).then(x=>x.json())));results.forEach(x=>{if(x.status==='fulfilled'&&x.value?.id)loaded.push(x.value)})}return [...new Map(loaded.map(x=>[x.id,x])).values()]}
function applyLanguage(){document.documentElement.lang=lang;q.placeholder=lang==='de'?'z. B. Kabel, Metall, ARC ...':'e.g. Wires, Metal, ARC ...';questQ.placeholder=tr('questPlaceholder');deBtn.classList.toggle('active',lang==='de');enBtn.classList.toggle('active',lang==='en');localStorage.setItem('arcLang',lang);drawGoals();drawQuestHeader();drawQuests();drawSummary();drawItems()}
deBtn.addEventListener('click',()=>{lang='de';applyLanguage()});enBtn.addEventListener('click',()=>{lang='en';applyLanguage()});q.addEventListener('input',drawItems);questQ.addEventListener('input',drawQuests);questDrawer.addEventListener('toggle',()=>{drawQuestHeader();drawQuests()});document.querySelectorAll('.quest-filter').forEach(btn=>btn.addEventListener('click',()=>{questFilter=btn.dataset.filter;drawQuests()}));
async function loadFullCatalog(){let all=[],offset=0,total=null;while(true){const r=await fetch(`https://arcdata.mahcks.com/v1/items?full=true&offset=${offset}&limit=45`,{cache:'no-store'});if(!r.ok)throw new Error('catalog');const data=await r.json();if(total===null)total=Number(data.total??data.count??0)||null;all.push(...data.items);if(!data.next)break;offset+=45;if(offset>2000)throw new Error('guard')}const unique=[...new Map(all.map(i=>[i.id,i])).values()];if(total&&unique.length!==total)throw new Error('incomplete');return unique}
async function boot(){try{goals=await fetch('goals.json?v=293',{cache:'no-store'}).then(r=>r.json());items=await loadFullCatalog()}catch{items=await fetch('items.json?v=293',{cache:'no-store'}).then(r=>r.json());usingFallback=true}try{quests=await loadQuests()}catch{quests=[];questLoadError=true}applyLanguage()}boot();