// Validated local backup export/import without a server.
(()=>{
  const panel=document.getElementById('backupPanel'),exportButton=document.getElementById('backupExport'),importButton=document.getElementById('backupImport'),fileInput=document.getElementById('backupFile'),closeButton=document.getElementById('backupClose'),status=document.getElementById('backupStatus');if(!panel||!exportButton||!importButton||!fileInput||!closeButton||!status)return;
  const SCHEMA='ramas-field-tool-backup',FORMAT_VERSION=1,MAX_FILE_SIZE=500000,isRecord=v=>!!v&&typeof v==='object'&&!Array.isArray(v),blockedKeys=new Set(['__proto__','prototype','constructor']);
  const safeKeys=v=>isRecord(v)&&Object.keys(v).length<=5000&&Object.keys(v).every(k=>typeof k==='string'&&k.length<=180&&!blockedKeys.has(k));const finiteNumber=v=>typeof v==='number'&&Number.isFinite(v)&&v>=0&&v<=1000000000;
  const validRaidEntry=e=>isRecord(e)&&Object.keys(e).every(k=>['target','done','personal','found'].includes(k))&&typeof e.done==='boolean'&&finiteNumber(e.target)&&(e.personal===undefined||typeof e.personal==='boolean')&&(e.found===undefined||finiteNumber(e.found));
  const validPersonal=e=>isRecord(e)&&typeof e.itemId==='string'&&e.itemId.length<=180&&finiteNumber(e.target)&&e.target>=1&&['active','paused','done'].includes(e.status)&&Object.keys(e).every(k=>['itemId','target','status','source','completedAt'].includes(k));
  const validHistory=e=>isRecord(e)&&typeof e.kind==='string'&&e.kind.length<=80&&(!e.itemId||typeof e.itemId==='string')&&(!e.at||!Number.isNaN(Date.parse(e.at)));
  const RULES={arcLang:{type:'string',valid:v=>['de','en'].includes(v)},arcUiLanguage:{type:'string',valid:v=>['de','en','fr','es','it'].includes(v)},arcTheme:{type:'string',valid:v=>['dark','light'].includes(v)},arcPaletteSurface:{type:'string',valid:v=>['black','dark','light'].includes(v)},arcPaletteAccent:{type:'string',valid:v=>['orange','amber','green','cyan'].includes(v)},arcOwned:{type:'json',valid:v=>safeKeys(v)&&Object.values(v).every(finiteNumber)},arcActiveGoals:{type:'json',valid:v=>safeKeys(v)&&Object.values(v).every(e=>e===true)},arcQuestStatus:{type:'json',valid:v=>safeKeys(v)&&Object.values(v).every(e=>['open','active','done'].includes(e))},arc_blueprints_learned_v1:{type:'json',valid:v=>Array.isArray(v)&&v.length<=5000&&v.every(e=>typeof e==='string'&&e.length<=180)},arcSpawnMap:{type:'string',valid:v=>/^[a-z0-9-]{1,80}$/i.test(v)},arcNextRaid:{type:'json',valid:v=>safeKeys(v)&&Object.values(v).every(validRaidEntry)},arcPlanningPersonal:{type:'json',valid:v=>safeKeys(v)&&Object.values(v).every(validPersonal)},arcPlanningHistory:{type:'json',valid:v=>Array.isArray(v)&&v.length<=250&&v.every(validHistory)},arcPlanningMigrationV2:{type:'string',valid:v=>v==='1'},arcEventRegion:{type:'string',valid:v=>['europe','north-america','brazil','east-asia','oceania'].includes(v)},arcEventLead:{type:'string',valid:v=>['5','10','15','30'].includes(v)},arcEventReminders:{type:'json',valid:v=>Array.isArray(v)&&v.length<=100}};
  const COPY={de:{exported:'Backup wurde auf deinem Gerät gespeichert.',noData:'Es wurden noch keine App-Daten gefunden.',choose:'Wähle eine gültige Backup-Datei aus.',tooLarge:'Die Datei ist zu groß und wurde nicht geöffnet.',invalid:'Diese Datei ist kein gültiges Backup von Ramas Field Tool.',version:'Diese Backup-Version wird noch nicht unterstützt.',importConfirm:'Dieses Backup ersetzt deine derzeit gespeicherten App-Daten. Wirklich fortfahren?',imported:'Backup erfolgreich importiert. Die App wird neu geladen …',failed:'Das Backup konnte nicht importiert werden.'},en:{exported:'The backup was saved on your device.',noData:'No app data was found yet.',choose:'Choose a valid backup file.',tooLarge:'The file is too large and was not opened.',invalid:'This file is not a valid Ramas Field Tool backup.',version:'This backup version is not supported yet.',importConfirm:'This backup will replace your currently saved app data. Continue?',imported:'Backup imported successfully. Reloading the app …',failed:'The backup could not be imported.'},fr:{exported:'Sauvegarde enregistrée sur votre appareil.',noData:'Aucune donnée enregistrée.',choose:'Choisissez un fichier de sauvegarde valide.',tooLarge:'Le fichier est trop volumineux.',invalid:'Ce fichier n’est pas une sauvegarde valide.',version:'Cette version de sauvegarde n’est pas prise en charge.',importConfirm:'Cette sauvegarde remplacera vos données actuelles. Continuer ?',imported:'Sauvegarde importée. Rechargement …',failed:'Impossible d’importer la sauvegarde.'},es:{exported:'Copia guardada en tu dispositivo.',noData:'Aún no hay datos guardados.',choose:'Elige un archivo de copia válido.',tooLarge:'El archivo es demasiado grande.',invalid:'Este archivo no es una copia válida.',version:'Esta versión no es compatible.',importConfirm:'Esta copia sustituirá tus datos actuales. ¿Continuar?',imported:'Copia importada. Recargando …',failed:'No se pudo importar la copia.'},it:{exported:'Backup salvato sul dispositivo.',noData:'Nessun dato salvato.',choose:'Scegli un file di backup valido.',tooLarge:'Il file è troppo grande.',invalid:'Questo file non è un backup valido.',version:'Questa versione non è supportata.',importConfirm:'Questo backup sostituirà i dati attuali. Continuare?',imported:'Backup importato. Ricaricamento …',failed:'Impossibile importare il backup.'}};
  const language=()=>localStorage.getItem('arcUiLanguage')||'en',copy=()=>COPY[language()]||COPY.en,setStatus=(m,t='')=>{status.textContent=m;status.classList.toggle('is-success',t==='success');status.classList.toggle('is-error',t==='error')};
  function readCurrentData(){const data={};Object.entries(RULES).forEach(([key,rule])=>{const raw=localStorage.getItem(key);if(raw===null){data[key]=null;return}if(rule.type==='string'){data[key]=rule.valid(raw)?raw:null;return}try{const parsed=JSON.parse(raw);data[key]=rule.valid(parsed)?parsed:null}catch{data[key]=null}});return data}
  function exportBackup(){try{const data=readCurrentData(),backup={schema:SCHEMA,formatVersion:FORMAT_VERSION,app:'Ramas Field Tool',appVersion:document.querySelector('[data-app-version]')?.textContent?.trim()||'',exportedAt:new Date().toISOString(),data},blob=new Blob([JSON.stringify(backup,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`ramas-field-tool-backup-${new Date().toISOString().slice(0,10)}.json`;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);setStatus(Object.values(data).some(v=>v!==null)?copy().exported:copy().noData,'success')}catch(error){console.error('Backup export failed',error);setStatus(copy().failed,'error')}}
  function validateBackup(backup){const c=copy();if(!isRecord(backup)||backup.schema!==SCHEMA||backup.app!=='Ramas Field Tool'||!isRecord(backup.data))throw new Error(c.invalid);if(backup.formatVersion!==FORMAT_VERSION)throw new Error(c.version);const supplied=Object.keys(backup.data),allowed=Object.keys(RULES);if(!supplied.length||supplied.some(k=>!allowed.includes(k)))throw new Error(c.invalid);supplied.forEach(k=>{const v=backup.data[k];if(v!==null&&!RULES[k].valid(v))throw new Error(c.invalid)});return supplied}
  function applyBackup(data,keys){const allKeys=Object.keys(RULES),previous=Object.fromEntries(allKeys.map(k=>[k,localStorage.getItem(k)]));try{allKeys.forEach(key=>{if(!keys.includes(key)){localStorage.removeItem(key);return}const value=data[key];if(value===null){localStorage.removeItem(key);return}localStorage.setItem(key,RULES[key].type==='json'?JSON.stringify(value):value)});if(keys.includes('arcPlanningPersonal'))localStorage.setItem('arcPlanningMigrationV2','1')}catch(error){allKeys.forEach(k=>previous[k]===null?localStorage.removeItem(k):localStorage.setItem(k,previous[k]));throw error}}
  async function importBackup(file){const c=copy();if(!file){setStatus(c.choose,'error');return}if(file.size>MAX_FILE_SIZE){setStatus(c.tooLarge,'error');return}try{const backup=JSON.parse(await file.text()),keys=validateBackup(backup);if(!window.confirm(c.importConfirm))return;applyBackup(backup.data,keys);setStatus(c.imported,'success');setTimeout(()=>location.reload(),900)}catch(error){console.error('Backup import failed',error);setStatus(error?.message&&Object.values(c).includes(error.message)?error.message:c.failed,'error')}}
  exportButton.addEventListener('click',exportBackup);importButton.addEventListener('click',()=>fileInput.click());fileInput.addEventListener('change',async()=>{await importBackup(fileInput.files?.[0]);fileInput.value=''});closeButton.addEventListener('click',()=>{panel.open=false;panel.querySelector(':scope > summary')?.focus({preventScroll:true})});window.addEventListener('arc-language-change',()=>setStatus('')); 
})();