// Visible post-raid flow using the same requirements and stock as My Planning.
(()=>{
  const root=document.getElementById('planningSection');if(!root)return;
  const copy={de:['Raid beendet','Funde eintragen','Gefunden','Funde übernehmen','Nichts Relevantes gefunden','Abbrechen','Funde gespeichert. Dein Bedarf ist aktualisiert.','Für deine aktiven Ziele fehlt aktuell nichts.','Speichern fehlgeschlagen. Deine Eingaben bleiben erhalten.','Trage mindestens einen Fund ein.','Sammelziel erreicht'],en:['Raid finished','Log finds','Found','Apply finds','No relevant finds','Cancel','Finds saved. Your requirements are updated.','Nothing is missing for your active goals.','Saving failed. Your entries are kept.','Enter at least one find.','Collection goal reached'],fr:['Raid terminé','Saisir les trouvailles','Trouvé','Enregistrer les trouvailles','Aucune trouvaille utile','Annuler','Trouvailles enregistrées. Vos besoins sont actualisés.','Rien ne manque pour vos objectifs actifs.','Échec de l’enregistrement. Vos saisies sont conservées.','Saisissez au moins une trouvaille.','Objectif de collecte atteint'],es:['Raid terminado','Registrar hallazgos','Encontrado','Guardar hallazgos','Sin hallazgos relevantes','Cancelar','Hallazgos guardados. Tus necesidades están actualizadas.','No falta nada para tus objetivos activos.','Error al guardar. Se conservan tus entradas.','Introduce al menos un hallazgo.','Objetivo de colección alcanzado'],it:['Raid terminato','Registra ritrovamenti','Trovato','Applica ritrovamenti','Nessun ritrovamento utile','Annulla','Ritrovamenti salvati. I materiali necessari sono aggiornati.','Non manca nulla per gli obiettivi attivi.','Salvataggio non riuscito. I dati inseriti restano.','Inserisci almeno un ritrovamento.','Obiettivo di raccolta raggiunto']};
  const language=()=>localStorage.getItem('arcUiLanguage')||'en',c=()=>copy[language()]||copy.en;
  const button=document.createElement('button');button.id='planningRaidFinished';button.type='button';button.setAttribute('aria-expanded','false');button.setAttribute('aria-controls','planningRaidPanel');const panel=document.createElement('section');panel.id='planningRaidPanel';panel.hidden=true;panel.innerHTML='<h3></h3><div id="planningRaidFinds"></div><p role="status" aria-live="polite"></p><div class="planning-raid-buttons"><button type="button" data-raid-apply></button><button type="button" data-raid-nothing></button><button type="button" data-raid-cancel></button></div>';document.getElementById('planningMissing').before(button,panel);const list=panel.querySelector('#planningRaidFinds'),notice=panel.querySelector('[role=status]');
  const name=id=>{const item=typeof itemById==='function'?itemById(id):null;return item?.name?.[language()]||item?.[language()]||item?.name?.en||item?.en||item?.name?.de||item?.de||String(id).replaceAll('_',' ')};const close=()=>{panel.hidden=true;button.setAttribute('aria-expanded','false')};
  function labels(){const t=c();button.textContent=t[0];panel.querySelector('h3').textContent=t[1];panel.querySelector('[data-raid-apply]').textContent=t[3];panel.querySelector('[data-raid-nothing]').textContent=t[4];panel.querySelector('[data-raid-cancel]').textContent=t[5];list.querySelectorAll('[data-found-label]').forEach(el=>el.textContent=t[2]);list.querySelectorAll('[data-found-name]').forEach(el=>el.textContent=name(el.dataset.foundName))}
  button.addEventListener('click',()=>{if(!panel.hidden){close();return}list.replaceChildren();notice.textContent='';const rows=window.RFTPlanning.rows();for(const row of rows){const entry=document.createElement('div');entry.className='planning-raid-find';const title=document.createElement('strong');title.dataset.foundName=row.itemId;const controls=document.createElement('div');controls.className='planning-raid-quantity';const label=document.createElement('label'),caption=document.createElement('span'),input=document.createElement('input');caption.dataset.foundLabel='';input.type='number';input.min='0';input.max='999999';input.step='1';input.inputMode='numeric';input.value='0';input.dataset.raidFind=row.itemId;label.append(caption,input);for(const step of[-1,1]){const control=document.createElement('button');control.type='button';control.textContent=step<0?'−':'+';control.addEventListener('click',()=>input.value=String(Math.min(999999,Math.max(0,(Number(input.value)||0)+step))));if(step<0)controls.append(control);else controls.append(label,control)}entry.append(title,controls);list.append(entry)}panel.querySelector('[data-raid-apply]').disabled=!rows.length;if(!rows.length)notice.textContent=c()[7];labels();panel.hidden=false;button.setAttribute('aria-expanded','true');list.querySelector('input')?.focus({preventScroll:true})});
  panel.querySelector('[data-raid-cancel]').addEventListener('click',close);panel.querySelector('[data-raid-nothing]').addEventListener('click',()=>{close();document.getElementById('planningStatus').textContent=c()[4]});panel.querySelector('[data-raid-apply]').addEventListener('click',()=>{const inputs=[...list.querySelectorAll('[data-raid-find]')];if(inputs.some(input=>!input.checkValidity())){inputs.find(input=>!input.checkValidity()).reportValidity();return}const updates=inputs.map(input=>[input.dataset.raidFind,Number(input.value)]).filter(([,amount])=>Number.isInteger(amount)&&amount>0);if(!updates.length){notice.textContent=c()[9];return}try{const next={...owned};for(const[id,amount]of updates)next[id]=(Number(next[id])||0)+amount;localStorage.setItem('arcOwned',JSON.stringify(next));for(const[id]of updates)owned[id]=next[id]}catch{notice.textContent=c()[8];return}const completed=window.RFTPlanning.completeReachedPersonal();close();if(typeof drawSummary==='function')drawSummary();if(typeof drawItems==='function')drawItems();window.dispatchEvent(new Event('planning-changed'));document.getElementById('planningStatus').textContent=completed.length?completed.map(goal=>`${c()[10]}: ${goal.target} ${name(goal.itemId)}.`).join(' '):c()[6]});
  document.getElementById('planningTabGoals').addEventListener('click',()=>{button.hidden=true;close()});document.getElementById('planningTabMissing').addEventListener('click',()=>button.hidden=false);window.addEventListener('arc-language-change',labels);labels();
})();
