// My Planning: one user-facing flow over the existing local data.
(()=>{
  const root=document.getElementById('planningSection');if(!root)return;
  const missing=document.getElementById('planningMissing'),goalsPane=document.getElementById('planningGoals'),tabMissing=document.getElementById('planningTabMissing'),tabGoals=document.getElementById('planningTabGoals'),status=document.getElementById('planningStatus');
  const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const uiLang=()=>localStorage.getItem('arcUiLanguage')||((typeof lang!=='undefined'&&lang)||'en');
  const COPY={de:{empty:'Für deine aktiven Ziele fehlt aktuell nichts.',need:'benötigt',owned:'vorhanden',left:'fehlen',usage:'Wofür benötigt',stock:'Bestand ändern',find:'Fund hinzufügen',add:'Hinzufügen',pause:'Pausieren',resume:'Fortsetzen',remove:'Entfernen',edit:'Zielmenge ändern',saved:'Gespeichert.',saveError:'Speichern fehlgeschlagen. Eingaben bleiben erhalten.',noPersonal:'Noch kein persönliches Sammelziel.',exists:'Für dieses Item besteht bereits ein Sammelziel.',reached:'Sammelziel erreicht',undo:'Rückgängig',search:'Item suchen …'},en:{empty:'Nothing is currently missing for your active goals.',need:'required',owned:'owned',left:'missing',usage:'Used for',stock:'Change stock',find:'Add find',add:'Add',pause:'Pause',resume:'Resume',remove:'Remove',edit:'Change target',saved:'Saved.',saveError:'Saving failed. Entries are kept.',noPersonal:'No personal collection goal yet.',exists:'A collection goal already exists for this item.',reached:'Collection goal reached',undo:'Undo',search:'Search item …'},fr:{empty:'Rien ne manque actuellement pour vos objectifs actifs.',need:'requis',owned:'possédé',left:'manquant',usage:'Utilisé pour',stock:'Modifier le stock',find:'Ajouter une trouvaille',add:'Ajouter',pause:'Pause',resume:'Reprendre',remove:'Supprimer',edit:'Modifier la quantité',saved:'Enregistré.',saveError:'Échec de l’enregistrement. Les saisies sont conservées.',noPersonal:'Aucun objectif personnel.',exists:'Un objectif existe déjà pour cet objet.',reached:'Objectif de collecte atteint',undo:'Annuler',search:'Rechercher un objet …'},es:{empty:'Ahora mismo no falta nada para tus objetivos activos.',need:'necesario',owned:'disponible',left:'falta',usage:'Se necesita para',stock:'Cambiar existencias',find:'Añadir hallazgo',add:'Añadir',pause:'Pausar',resume:'Continuar',remove:'Eliminar',edit:'Cambiar objetivo',saved:'Guardado.',saveError:'Error al guardar. Se conservan las entradas.',noPersonal:'Aún no hay objetivos personales.',exists:'Ya existe un objetivo para este objeto.',reached:'Objetivo de colección alcanzado',undo:'Deshacer',search:'Buscar objeto …'},it:{empty:'Al momento non manca nulla per i tuoi obiettivi attivi.',need:'necessari',owned:'posseduti',left:'mancanti',usage:'Necessario per',stock:'Modifica scorte',find:'Aggiungi ritrovamento',add:'Aggiungi',pause:'Pausa',resume:'Riprendi',remove:'Rimuovi',edit:'Modifica obiettivo',saved:'Salvato.',saveError:'Salvataggio non riuscito. I dati inseriti restano.',noPersonal:'Nessun obiettivo di raccolta personale.',exists:'Esiste già un obiettivo per questo oggetto.',reached:'Obiettivo di raccolta raggiunto',undo:'Annulla',search:'Cerca oggetto …'}};
  const STATIC={de:{title:'Meine Planung',subtitle:'Ziele · Fehlendes · Funde',missing:'Was fehlt mir?',goals:'Meine Ziele',personal:'Persönliche Sammelziele',item:'Item',amount:'Zielmenge',categories:['Sammelziele','Werkstatt','Quests'],active:'Aktiv',paused:'Pausiert',done:'Erledigt'},en:{title:'My planning',subtitle:'Goals · Missing items · Finds',missing:'What am I missing?',goals:'My goals',personal:'Personal collection goals',item:'Item',amount:'Target quantity',categories:['Collection','Workshop','Quests'],active:'Active',paused:'Paused',done:'Done'},fr:{title:'Ma planification',subtitle:'Objectifs · Objets manquants · Trouvailles',missing:'Que me manque-t-il ?',goals:'Mes objectifs',personal:'Objectifs de collecte personnels',item:'Objet',amount:'Quantité cible',categories:['Collecte','Atelier','Quêtes'],active:'Actif',paused:'En pause',done:'Terminé'},es:{title:'Mi planificación',subtitle:'Objetivos · Objetos faltantes · Hallazgos',missing:'¿Qué me falta?',goals:'Mis objetivos',personal:'Objetivos de colección personales',item:'Objeto',amount:'Cantidad objetivo',categories:['Colección','Taller','Misiones'],active:'Activo',paused:'Pausado',done:'Completado'},it:{title:'La mia pianificazione',subtitle:'Obiettivi · Oggetti mancanti · Ritrovamenti',missing:'Cosa mi manca?',goals:'I miei obiettivi',personal:'Obiettivi di raccolta personali',item:'Oggetto',amount:'Quantità obiettivo',categories:['Raccolta','Banco da lavoro','Missioni'],active:'Attivo',paused:'In pausa',done:'Completato'}};
  const c=()=>COPY[uiLang()]||COPY.en,strings=()=>STATIC[uiLang()]||STATIC.en;
  const name=id=>{const item=typeof itemById==='function'?itemById(id):null;if(!item)return String(id).replaceAll('_',' ');const language=uiLang(),names=item.name;return (names&&typeof names==='object'?(names[language]||names.en||item[language]||item.en||names.de):item[language]||item.en||names||item.de)||String(id).replaceAll('_',' ')};
  const drafts=new Map();let openDetails=new Set(),lastRemoved=null;
  function capture(){missing.querySelectorAll('[data-plan-item]').forEach(row=>{const id=row.dataset.planItem;drafts.set(id,{stock:row.querySelector('[data-stock]')?.value??'',find:row.querySelector('[data-find]')?.value??'0'});if(row.querySelector('details')?.open)openDetails.add(id);else openDetails.delete(id)})}
  function syncLabels(){const copy=strings(),tile=document.querySelector('[data-app-target="planningSection"]');if(tile?.querySelector('b'))tile.querySelector('b').textContent=copy.title;if(tile?.querySelector('small'))tile.querySelector('small').textContent=copy.subtitle;if(root.classList.contains('launcher-active')){const title=document.getElementById('detailTitle'),detailStatus=document.getElementById('detailStatus');if(title)title.textContent=copy.title;if(detailStatus)detailStatus.textContent=copy.subtitle}tabMissing.textContent=copy.missing;tabGoals.textContent=copy.goals;document.querySelector('#planningPersonalGroup h3').textContent=copy.personal;const search=document.getElementById('planningPersonalSearch'),item=document.getElementById('planningPersonalItem'),amount=document.getElementById('planningPersonalAmount');search.placeholder=c().search;const setLabel=(control,text)=>{const label=control?.closest('label');if(label?.firstChild)label.firstChild.nodeValue=text};setLabel(search,c().search.replace(/\s*…$/,''));setLabel(item,copy.item);setLabel(amount,copy.amount);document.getElementById('planningPersonalAdd').textContent=c().add;document.querySelectorAll('[data-goal-category]').forEach((button,i)=>button.textContent=copy.categories[i]);document.querySelector('.planning-categories')?.setAttribute('aria-label',copy.goals)}
  function saveStock(id,value,add=false){const n=Number(value);if(!Number.isInteger(n)||n<0){status.textContent=c().saveError;return}try{saveOwned(id,add?(Number(owned[id])||0)+n:n);if(add)drafts.set(id,{stock:String(owned[id]||0),find:'0'});window.RFTPlanning?.completeReachedPersonal();status.textContent=c().saved;render()}catch{status.textContent=c().saveError}}
  function renderMissing(){capture();const rows=window.RFTPlanning?.rows()||[];if(!rows.length){missing.innerHTML=`<div class="planning-empty">${esc(c().empty)}</div>`;return}missing.innerHTML=rows.sort((a,b)=>name(a.itemId).localeCompare(name(b.itemId))).map(row=>{const draft=drafts.get(row.itemId)||{stock:String(row.owned),find:'0'};return `<article class="planning-item" data-plan-item="${esc(row.itemId)}"><div class="planning-item-head"><strong>${esc(name(row.itemId))}</strong><b>${row.missing} ${esc(c().left)}</b></div><div class="planning-counts"><span>${esc(c().need)} <b>${row.required}</b></span><span>${esc(c().owned)} <b>${row.owned}</b></span></div><details ${openDetails.has(row.itemId)?'open':''}><summary>${esc(c().usage)}</summary><div>${row.reasons.map(reason=>esc(String(reason).replace(/^Personal:/,strings().personal+':'))).join('<br>')}</div></details><div class="planning-actions"><label>${esc(c().stock)}<input data-stock type="number" min="0" step="1" inputmode="numeric" value="${esc(draft.stock)}"></label><label>${esc(c().find)}<input data-find type="number" min="0" step="1" inputmode="numeric" value="${esc(draft.find)}"></label><button type="button" data-apply-find>${esc(c().add)}</button></div></article>`}).join('')}
  function renderPersonal(){const box=document.getElementById('planningPersonalList'),entries=Object.values(window.RFTPlanning?.personalGoals()||{});box.innerHTML=entries.length?entries.map(goal=>`<div class="planning-personal-row" data-personal="${esc(goal.itemId)}"><span><strong>${esc(name(goal.itemId))}</strong><small>${goal.target} · ${esc(strings()[goal.status]||goal.status)}</small></span>${goal.status!=='done'?`<button data-personal-toggle type="button">${esc(goal.status==='paused'?c().resume:c().pause)}</button>`:''}<button data-personal-edit type="button">${esc(c().edit)}</button><button data-personal-remove type="button">${esc(c().remove)}</button></div>`).join(''):`<div class="planning-empty">${esc(c().noPersonal)}</div>`}
  function render(){renderMissing();renderPersonal();syncLabels()}
  function show(which){const isMissing=which==='missing';missing.hidden=!isMissing;goalsPane.hidden=isMissing;tabMissing.setAttribute('aria-selected',String(isMissing));tabGoals.setAttribute('aria-selected',String(!isMissing));const raidButton=document.getElementById('planningRaidFinished');if(raidButton)raidButton.hidden=!isMissing;window.RFTPlanningIntegratedSources?.setVisible(!isMissing)}
  window.RFTPlanningShow=show;tabMissing.addEventListener('click',()=>show('missing'));tabGoals.addEventListener('click',()=>show('goals'));
  missing.addEventListener('input',capture);missing.addEventListener('toggle',capture,true);missing.addEventListener('change',e=>{const row=e.target.closest('[data-plan-item]');if(row&&e.target.matches('[data-stock]'))saveStock(row.dataset.planItem,e.target.value,false)});missing.addEventListener('click',e=>{const button=e.target.closest('[data-apply-find]');if(!button)return;const row=button.closest('[data-plan-item]'),input=row.querySelector('[data-find]');saveStock(row.dataset.planItem,input.value,true)});
  document.getElementById('planningPersonalAdd').addEventListener('click',()=>{const select=document.getElementById('planningPersonalItem'),amount=document.getElementById('planningPersonalAmount');if(!select.value)return;try{const existing=window.RFTPlanning.personalGoals()[select.value];if(existing){status.textContent=c().exists;return}window.RFTPlanning.setPersonal(select.value,amount.value);const completed=window.RFTPlanning.completeReachedPersonal();status.textContent=completed.length?`${c().reached}: ${completed[0].target} ${name(completed[0].itemId)}.`:c().saved;render()}catch{status.textContent=c().saveError}});
  document.getElementById('planningPersonalList').addEventListener('click',e=>{const row=e.target.closest('[data-personal]');if(!row)return;const personal=window.RFTPlanning.personalGoals()[row.dataset.personal];try{if(e.target.closest('[data-personal-remove]')){lastRemoved=window.RFTPlanning.removePersonal(row.dataset.personal);status.innerHTML=`${esc(c().saved)} <button type="button" id="planningUndoRemove">${esc(c().undo)}</button>`}else if(e.target.closest('[data-personal-toggle]'))window.RFTPlanning.setPersonalStatus(row.dataset.personal,personal.status==='paused'?'active':'paused');else if(e.target.closest('[data-personal-edit]')){const next=prompt(`${c().edit}: ${name(row.dataset.personal)}`,String(personal.target));if(next===null)return;window.RFTPlanning.updatePersonal(row.dataset.personal,next);window.RFTPlanning.completeReachedPersonal()}render()}catch{status.textContent=c().saveError}});
  status.addEventListener('click',e=>{if(e.target.id==='planningUndoRemove'&&lastRemoved){window.RFTPlanning.restorePersonal(lastRemoved);lastRemoved=null;status.textContent=c().saved;render()}});
  function populateItems(){const select=document.getElementById('planningPersonalItem'),search=document.getElementById('planningPersonalSearch');if(!select||typeof items==='undefined'||!Array.isArray(items)||!items.length)return;const current=select.value,needle=(search?.value||'').trim().toLocaleLowerCase();const filtered=items.filter(item=>!needle||name(item.id).toLocaleLowerCase().includes(needle)).sort((a,b)=>name(a.id).localeCompare(name(b.id))).slice(0,200);select.innerHTML='<option value=""></option>'+filtered.map(item=>`<option value="${esc(item.id)}">${esc(name(item.id))}</option>`).join('');if(filtered.some(i=>i.id===current))select.value=current}
  document.getElementById('planningPersonalSearch').addEventListener('input',populateItems);
  let catalogReference=null;setInterval(()=>{if(typeof items!=='undefined'&&Array.isArray(items)&&items.length&&items!==catalogReference){catalogReference=items;populateItems();render()}},500);
  window.RFTPlanningUI={syncLabels,render};window.addEventListener('arc-language-change',()=>{capture();populateItems();render();status.textContent=''});window.addEventListener('planning-changed',render);window.addEventListener('raid-goals-completed',render);window.addEventListener('storage',render);setTimeout(()=>{populateItems();render()},600);show('missing');syncLabels();
})();
