// My Planning: one user-facing flow over the existing local data.
(()=>{
  const root=document.getElementById('planningSection');if(!root)return;
  const missing=document.getElementById('planningMissing'),goalsPane=document.getElementById('planningGoals');
  const tabMissing=document.getElementById('planningTabMissing'),tabGoals=document.getElementById('planningTabGoals');
  const allToggle=document.getElementById('planningShowAll'),status=document.getElementById('planningStatus');
  const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const uiLang=()=>localStorage.getItem('arcUiLanguage')||((typeof lang!=='undefined'&&lang)||'en');
  const COPY={de:{empty:'Für deine aktiven Ziele fehlt aktuell nichts.',need:'benötigt',owned:'vorhanden',left:'fehlen',usage:'Wofür benötigt',stock:'Bestand ändern',find:'Fund hinzufügen',add:'Hinzufügen',pause:'Pausieren',resume:'Fortsetzen',remove:'Entfernen',saved:'Gespeichert.',saveError:'Speichern fehlgeschlagen.',noPersonal:'Noch kein persönliches Sammelziel.'},en:{empty:'Nothing is currently missing for your active goals.',need:'required',owned:'owned',left:'missing',usage:'Used for',stock:'Change stock',find:'Add find',add:'Add',pause:'Pause',resume:'Resume',remove:'Remove',saved:'Saved.',saveError:'Saving failed.',noPersonal:'No personal collection goal yet.'},fr:{empty:'Rien ne manque actuellement pour vos objectifs actifs.',need:'requis',owned:'possédé',left:'manquant',usage:'Utilisé pour',stock:'Modifier le stock',find:'Ajouter une trouvaille',add:'Ajouter',pause:'Pause',resume:'Reprendre',remove:'Supprimer',saved:'Enregistré.',saveError:'Échec de l’enregistrement.',noPersonal:'Aucun objectif personnel.'},es:{empty:'Ahora mismo no falta nada para tus objetivos activos.',need:'necesario',owned:'disponible',left:'falta',usage:'Se necesita para',stock:'Cambiar existencias',find:'Añadir hallazgo',add:'Añadir',pause:'Pausar',resume:'Continuar',remove:'Eliminar',saved:'Guardado.',saveError:'Error al guardar.',noPersonal:'Aún no hay objetivos personales.'}};
  const c=()=>COPY[uiLang()]||COPY.en;
  const STATIC={
    de:{title:'Meine Planung',subtitle:'Ziele · Fehlendes · Funde',missing:'Was fehlt mir?',goals:'Meine Ziele',all:'Alle benötigten Items',personal:'Persönliche Sammelziele',item:'Item',amount:'Zielmenge',categories:['Sammelziele','Werkstatt','Quests'],active:'Aktiv',paused:'Pausiert',done:'Erledigt'},
    en:{title:'My planning',subtitle:'Goals · Missing items · Finds',missing:'What am I missing?',goals:'My goals',all:'All required items',personal:'Personal collection goals',item:'Item',amount:'Target quantity',categories:['Collection','Workshop','Quests'],active:'Active',paused:'Paused',done:'Done'},
    fr:{title:'Ma planification',subtitle:'Objectifs · Objets manquants · Trouvailles',missing:'Que me manque-t-il ?',goals:'Mes objectifs',all:'Tous les objets requis',personal:'Objectifs de collecte personnels',item:'Objet',amount:'Quantité cible',categories:['Collecte','Atelier','Quêtes'],active:'Actif',paused:'En pause',done:'Terminé'},
    es:{title:'Mi planificación',subtitle:'Objetivos · Objetos faltantes · Hallazgos',missing:'¿Qué me falta?',goals:'Mis objetivos',all:'Todos los objetos necesarios',personal:'Objetivos de colección personales',item:'Objeto',amount:'Cantidad objetivo',categories:['Colección','Taller','Misiones'],active:'Activo',paused:'En pausa',done:'Completado'}
  };
  const strings=()=>STATIC[uiLang()]||STATIC.en;
  const name=id=>{const item=typeof itemById==='function'?itemById(id):null;if(!item)return String(id).replaceAll('_',' ');const language=uiLang(),names=item.name;return (names&&typeof names==='object'?(names[language]||names.en||item[language]||item.en||names.de):item[language]||item.en||names||item.de)||id};
  const setText=(node,value)=>{if(node&&node.textContent!==value)node.textContent=value};
  function syncLabels(){const copy=strings(),tile=document.querySelector('[data-app-target="planningSection"]');setText(tile?.querySelector('b'),copy.title);setText(tile?.querySelector('small'),copy.subtitle);if(root.classList.contains('launcher-active')){setText(document.getElementById('detailTitle'),copy.title);setText(document.getElementById('detailStatus'),copy.subtitle)}setText(tabMissing,copy.missing);setText(tabGoals,copy.goals);setText(allToggle.parentElement.querySelector('span'),copy.all);setText(document.querySelector('#planningPersonalGroup h3'),copy.personal);const labels=document.querySelectorAll('.planning-personal-add label');if(labels[0]?.firstChild)labels[0].firstChild.nodeValue=copy.item;if(labels[1]?.firstChild)labels[1].firstChild.nodeValue=copy.amount;setText(document.getElementById('planningPersonalAdd'),c().add);document.querySelectorAll('[data-goal-category]').forEach((button,i)=>setText(button,copy.categories[i]));document.querySelector('.planning-categories')?.setAttribute('aria-label',copy.goals)}
  function saveStock(id,value,add=false){try{const next=Math.max(0,Math.floor(Number(value)||0));saveOwned(id,add?(Number(owned[id])||0)+next:next);status.textContent=c().saved;render()}catch{status.textContent=c().saveError}}
  function renderMissing(){const rows=window.RFTPlanning?.rows({all:allToggle.checked})||[];if(!rows.length){missing.innerHTML=`<div class="planning-empty">${esc(c().empty)}</div>`;return}missing.innerHTML=rows.sort((a,b)=>name(a.itemId).localeCompare(name(b.itemId))).map(row=>`<article class="planning-item" data-plan-item="${esc(row.itemId)}"><div class="planning-item-head"><strong>${esc(name(row.itemId))}</strong><b>${row.missing} ${esc(c().left)}</b></div><div class="planning-counts"><span>${esc(c().need)} <b>${row.required}</b></span><span>${esc(c().owned)} <b>${row.owned}</b></span></div><details><summary>${esc(c().usage)}</summary><div>${row.reasons.map(reason=>esc(String(reason).replace(/^Personal:/,strings().personal+':'))).join('<br>')}</div></details><div class="planning-actions"><label>${esc(c().stock)}<input data-stock type="number" min="0" inputmode="numeric" value="${row.owned}"></label><label>${esc(c().find)}<input data-find type="number" min="0" inputmode="numeric" value="0"></label><button type="button" data-apply-find>${esc(c().add)}</button></div></article>`).join('')}
  function renderPersonal(){const box=document.getElementById('planningPersonalList'),personal=window.RFTPlanning?.personalGoals()||{},entries=Object.values(personal);box.innerHTML=entries.length?entries.map(goal=>`<div class="planning-personal-row" data-personal="${esc(goal.itemId)}"><span><strong>${esc(name(goal.itemId))}</strong><small>${goal.target} · ${esc(strings()[goal.status]||goal.status)}</small></span><button data-personal-toggle type="button">${esc(goal.status==='paused'?c().resume:c().pause)}</button><button data-personal-remove type="button">${esc(c().remove)}</button></div>`).join(''):`<div class="planning-empty">${esc(c().noPersonal)}</div>`}
  function render(){renderMissing();renderPersonal();syncLabels()}
  function show(which){const isMissing=which==='missing';missing.hidden=!isMissing;goalsPane.hidden=isMissing;root.querySelector('.planning-filters').hidden=!isMissing;tabMissing.setAttribute('aria-selected',String(isMissing));tabGoals.setAttribute('aria-selected',String(!isMissing));window.RFTPlanningIntegratedSources?.setVisible(!isMissing)}
  tabMissing.addEventListener('click',()=>show('missing'));tabGoals.addEventListener('click',()=>show('goals'));allToggle.addEventListener('change',renderMissing);
  missing.addEventListener('change',e=>{const row=e.target.closest('[data-plan-item]');if(row&&e.target.matches('[data-stock]'))saveStock(row.dataset.planItem,e.target.value,false)});missing.addEventListener('click',e=>{const button=e.target.closest('[data-apply-find]');if(!button)return;const row=button.closest('[data-plan-item]'),input=row.querySelector('[data-find]');saveStock(row.dataset.planItem,input.value,true)});
  document.getElementById('planningPersonalAdd').addEventListener('click',()=>{const select=document.getElementById('planningPersonalItem'),amount=document.getElementById('planningPersonalAmount');if(!select.value)return;try{window.RFTPlanning.setPersonal(select.value,amount.value);status.textContent=c().saved;render()}catch{status.textContent=c().saveError}});
  document.getElementById('planningPersonalList').addEventListener('click',e=>{const row=e.target.closest('[data-personal]');if(!row)return;const personal=window.RFTPlanning.personalGoals()[row.dataset.personal];try{if(e.target.closest('[data-personal-remove]'))window.RFTPlanning.removePersonal(row.dataset.personal);else if(e.target.closest('[data-personal-toggle]'))window.RFTPlanning.setPersonal(row.dataset.personal,personal.target,personal.status==='paused'?'active':'paused');render()}catch{status.textContent=c().saveError}});
  function populateItems(){const select=document.getElementById('planningPersonalItem');if(!select||typeof items==='undefined'||!Array.isArray(items)||!items.length)return;const current=select.value;select.innerHTML='<option value=""></option>'+items.slice().sort((a,b)=>name(a.id).localeCompare(name(b.id))).map(item=>`<option value="${esc(item.id)}">${esc(name(item.id))}</option>`).join('');select.value=current}
  let catalogReference=null;setInterval(()=>{if(typeof items!=='undefined'&&Array.isArray(items)&&items.length&&items!==catalogReference){catalogReference=items;populateItems();render()}},500);
  window.RFTPlanningUI={syncLabels};window.addEventListener('arc-language-change',()=>{populateItems();render();status.textContent=''});window.addEventListener('planning-changed',render);window.addEventListener('raid-goals-completed',render);window.addEventListener('storage',render);document.addEventListener('click',event=>{if(root.contains(event.target))return;setTimeout(()=>{populateItems();render()},0)});setTimeout(()=>{populateItems();render()},600);show('missing');syncLabels();
})();
