// My Planning: one user-facing flow over the existing local data.
(()=>{
  const root=document.getElementById('planningSection');if(!root)return;
  const missing=document.getElementById('planningMissing'),goalsPane=document.getElementById('planningGoals');
  const tabMissing=document.getElementById('planningTabMissing'),tabGoals=document.getElementById('planningTabGoals');
  const status=document.getElementById('planningStatus');
  const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const uiLang=()=>localStorage.getItem('arcUiLanguage')||((typeof lang!=='undefined'&&lang)||'en');
  const COPY={de:{empty:'Für deine aktiven Ziele fehlt aktuell nichts.',need:'benötigt',owned:'vorhanden',left:'fehlen',usage:'Wofür benötigt',stock:'Bestand ändern',find:'Fund hinzufügen',add:'Hinzufügen',pause:'Pausieren',resume:'Fortsetzen',remove:'Entfernen',saved:'Gespeichert.',saveError:'Speichern fehlgeschlagen.',noPersonal:'Noch kein persönliches Sammelziel.'},en:{empty:'Nothing is currently missing for your active goals.',need:'required',owned:'owned',left:'missing',usage:'Used for',stock:'Change stock',find:'Add find',add:'Add',pause:'Pause',resume:'Resume',remove:'Remove',saved:'Saved.',saveError:'Saving failed.',noPersonal:'No personal collection goal yet.'},fr:{empty:'Rien ne manque actuellement pour vos objectifs actifs.',need:'requis',owned:'possédé',left:'manquant',usage:'Utilisé pour',stock:'Modifier le stock',find:'Ajouter une trouvaille',add:'Ajouter',pause:'Pause',resume:'Reprendre',remove:'Supprimer',saved:'Enregistré.',saveError:'Échec de l’enregistrement.',noPersonal:'Aucun objectif personnel.'},es:{empty:'Ahora mismo no falta nada para tus objetivos activos.',need:'necesario',owned:'disponible',left:'falta',usage:'Se necesita para',stock:'Cambiar existencias',find:'Añadir hallazgo',add:'Añadir',pause:'Pausar',resume:'Continuar',remove:'Eliminar',saved:'Guardado.',saveError:'Error al guardar.',noPersonal:'Aún no hay objetivos personales.'},it:{empty:'Al momento non manca nulla per i tuoi obiettivi attivi.',need:'necessari',owned:'posseduti',left:'mancanti',usage:'Necessario per',stock:'Modifica scorte',find:'Aggiungi ritrovamento',add:'Aggiungi',pause:'Pausa',resume:'Riprendi',remove:'Rimuovi',saved:'Salvato.',saveError:'Salvataggio non riuscito.',noPersonal:'Nessun obiettivo di raccolta personale.'}};
  const c=()=>COPY[uiLang()]||COPY.en;
  const EXTRA={
    de:{search:'Item suchen',noMatch:'Keine passenden Items.',change:'Zielmenge ändern',existing:'Bestehende Zielmenge',complete:'Sammelziel erreicht',open:'Ziel in Meine Planung öffnen',invalid:'Bitte eine gültige ganze Menge eingeben.',none:'Keine aktiven Ziele. Wähle unter „Meine Ziele“ ein Sammelziel, eine Werkstattstufe oder eine Quest.',tasks:'Aktive Quests haben keinen Materialbedarf. Erledige ihre Aufgaben im Spiel und bestätige sie unter „Meine Ziele“.',ready:'Alle benötigten Items sind vorhanden. Quests und Werkstattstufen kannst du nach Erledigung im Spiel bestätigen.'},
    en:{search:'Search items',noMatch:'No matching items.',change:'Change target quantity',existing:'Existing target quantity',complete:'Collection goal reached',open:'Open goal in My planning',invalid:'Enter a valid whole quantity.',none:'No active goals. Choose a collection goal, workshop level or quest under My goals.',tasks:'Active quests have no material requirements. Complete their tasks in the game and confirm them under My goals.',ready:'All required items are available. Confirm quests and workshop levels after completing them in the game.'},
    fr:{search:'Rechercher un objet',noMatch:'Aucun objet correspondant.',change:'Modifier la quantité cible',existing:'Quantité cible actuelle',complete:'Objectif de collecte atteint',open:'Ouvrir dans Ma planification',invalid:'Saisissez une quantité entière valide.',none:'Aucun objectif actif. Choisissez un objectif de collecte, un niveau d’atelier ou une quête dans Mes objectifs.',tasks:'Les quêtes actives ne nécessitent aucun matériau. Effectuez leurs tâches dans le jeu puis confirmez dans Mes objectifs.',ready:'Tous les objets requis sont disponibles. Confirmez les quêtes et niveaux d’atelier après les avoir terminés dans le jeu.'},
    es:{search:'Buscar objeto',noMatch:'No hay objetos coincidentes.',change:'Cambiar cantidad objetivo',existing:'Cantidad objetivo actual',complete:'Objetivo de colección alcanzado',open:'Abrir en Mi planificación',invalid:'Introduce una cantidad entera válida.',none:'No hay objetivos activos. Elige un objetivo de colección, nivel de taller o misión en Mis objetivos.',tasks:'Las misiones activas no requieren materiales. Completa sus tareas en el juego y confirma en Mis objetivos.',ready:'Todos los objetos necesarios están disponibles. Confirma las misiones y niveles de taller después de completarlos en el juego.'},
    it:{search:'Cerca oggetto',noMatch:'Nessun oggetto corrispondente.',change:'Modifica quantità obiettivo',existing:'Quantità obiettivo attuale',complete:'Obiettivo di raccolta raggiunto',open:'Apri in La mia pianificazione',invalid:'Inserisci una quantità intera valida.',none:'Nessun obiettivo attivo. Scegli un obiettivo di raccolta, un livello del banco da lavoro o una missione in I miei obiettivi.',tasks:'Le missioni attive non richiedono materiali. Completa le attività nel gioco e conferma in I miei obiettivi.',ready:'Tutti gli oggetti necessari sono disponibili. Conferma missioni e livelli del banco da lavoro dopo averli completati nel gioco.'}
  };
  const x=()=>EXTRA[uiLang()]||EXTRA.en;
  const drafts=new Map(),openDetails=new Set();
  const completedMessage=goals=>goals.map(goal=>`${x().complete}: ${goal.target} × ${name(goal.itemId)}.`).join(' ');
  const goalLabel=id=>window.RFTPlanning.personalGoals()[id]?x().change:({de:'Sammelziel hinzufügen',en:'Add collection goal',fr:'Ajouter un objectif de collecte',es:'Añadir objetivo de colección',it:'Aggiungi obiettivo di raccolta'}[uiLang()]||'Add collection goal');

  const STATIC={
    de:{title:'Meine Planung',subtitle:'Ziele · Fehlendes · Funde',missing:'Was fehlt mir?',goals:'Meine Ziele',all:'Alle benötigten Items',personal:'Persönliche Sammelziele',item:'Item',amount:'Zielmenge',categories:['Sammelziele','Werkstatt','Quests'],active:'Aktiv',paused:'Pausiert',done:'Erledigt'},
    en:{title:'My planning',subtitle:'Goals · Missing items · Finds',missing:'What am I missing?',goals:'My goals',all:'All required items',personal:'Personal collection goals',item:'Item',amount:'Target quantity',categories:['Collection','Workshop','Quests'],active:'Active',paused:'Paused',done:'Done'},
    fr:{title:'Ma planification',subtitle:'Objectifs · Objets manquants · Trouvailles',missing:'Que me manque-t-il ?',goals:'Mes objectifs',all:'Tous les objets requis',personal:'Objectifs de collecte personnels',item:'Objet',amount:'Quantité cible',categories:['Collecte','Atelier','Quêtes'],active:'Actif',paused:'En pause',done:'Terminé'},
    es:{title:'Mi planificación',subtitle:'Objetivos · Objetos faltantes · Hallazgos',missing:'¿Qué me falta?',goals:'Mis objetivos',all:'Todos los objetos necesarios',personal:'Objetivos de colección personales',item:'Objeto',amount:'Cantidad objetivo',categories:['Colección','Taller','Misiones'],active:'Activo',paused:'En pausa',done:'Completado'},
    it:{title:'La mia pianificazione',subtitle:'Obiettivi · Oggetti mancanti · Ritrovamenti',missing:'Cosa mi manca?',goals:'I miei obiettivi',all:'Tutti gli oggetti necessari',personal:'Obiettivi di raccolta personali',item:'Oggetto',amount:'Quantità obiettivo',categories:['Raccolta','Banco da lavoro','Missioni'],active:'Attivo',paused:'In pausa',done:'Completato'}
  };
  const strings=()=>STATIC[uiLang()]||STATIC.en;
  const name=id=>{const item=typeof itemById==='function'?itemById(id):null;if(!item)return String(id).replaceAll('_',' ');const language=uiLang(),names=item.name;return (names&&typeof names==='object'?(names[language]||names.en||item[language]||item.en||names.de):item[language]||item.en||names||item.de)||id};
  const setText=(node,value)=>{if(node&&node.textContent!==value)node.textContent=value};
  function syncLabels(){const copy=strings(),tile=document.querySelector('[data-app-target="planningSection"]');setText(tile?.querySelector('b'),copy.title);setText(tile?.querySelector('small'),copy.subtitle);if(root.classList.contains('launcher-active')){setText(document.getElementById('detailTitle'),copy.title);setText(document.getElementById('detailStatus'),copy.subtitle)}setText(tabMissing,copy.missing);setText(tabGoals,copy.goals);setText(document.querySelector('#planningPersonalGroup h3'),copy.personal);const itemLabel=document.getElementById('planningPersonalItem')?.parentElement,amountLabel=document.getElementById('planningPersonalAmount')?.parentElement;if(itemLabel?.firstChild)itemLabel.firstChild.nodeValue=copy.item;if(amountLabel?.firstChild)amountLabel.firstChild.nodeValue=copy.amount;setText(document.getElementById('planningPersonalAdd'),window.RFTPlanning.personalGoals()[document.getElementById('planningPersonalItem').value]?x().change:c().add);setText(document.querySelector('[data-picker-label]'),x().search);document.querySelectorAll('[data-goal-category]').forEach((button,i)=>setText(button,copy.categories[i]));document.querySelector('.planning-categories')?.setAttribute('aria-label',copy.goals)}
  function saveStock(id,value,add=false){
    const quantity=Number(value);if(!Number.isSafeInteger(quantity)||quantity<0){status.textContent=x().invalid;return}
    const draftKey=(add?'find:':'stock:')+id,previous=drafts.get(draftKey);drafts.delete(draftKey);
    try{const completed=saveOwned(id,add?(Number(owned[id])||0)+quantity:quantity)||[];status.textContent=[c().saved,completedMessage(completed)].filter(Boolean).join(' ');render()}catch{if(previous!==undefined)drafts.set(draftKey,previous);status.textContent=c().saveError}
  }
  function renderMissing(){const rows=window.RFTPlanning?.rows()||[];if(!rows.length){missing.innerHTML=`<div class="planning-empty">${esc(emptyMessage())}</div>`;return}missing.innerHTML=rows.sort((a,b)=>name(a.itemId).localeCompare(name(b.itemId))).map(row=>`<article class="planning-item" data-plan-item="${esc(row.itemId)}"><div class="planning-item-head"><strong>${esc(name(row.itemId))}</strong><b>${row.missing} ${esc(c().left)}</b></div><div class="planning-counts"><span>${esc(c().need)} <b>${row.required}</b></span><span>${esc(c().owned)} <b>${row.owned}</b></span></div><details ${openDetails.has(row.itemId)?'open':''}><summary>${esc(c().usage)}</summary><div>${row.reasons.map(reason=>esc(String(reason).replace(/^Personal:/,strings().personal+':'))).join('<br>')}</div></details><div class="planning-actions"><label>${esc(c().stock)}<input data-stock type="number" min="0" inputmode="numeric" step="1" max="999999999" value="${esc(drafts.get('stock:'+row.itemId)??row.owned)}"></label><label>${esc(c().find)}<input data-find type="number" min="0" step="1" max="999999" inputmode="numeric" value="${esc(drafts.get('find:'+row.itemId)??0)}"></label><button type="button" data-apply-find>${esc(c().add)}</button></div></article>`).join('')}
  function renderPersonal(){const box=document.getElementById('planningPersonalList'),personal=window.RFTPlanning?.personalGoals()||{},entries=Object.values(personal);box.innerHTML=entries.length?entries.map(goal=>`<div class="planning-personal-row" data-personal="${esc(goal.itemId)}"><span><strong>${esc(name(goal.itemId))}</strong><small>${goal.target} · ${esc(strings()[goal.status]||goal.status)}</small></span><label>${esc(c().stock)}<input data-personal-stock type="number" min="0" step="1" inputmode="numeric" value="${esc(drafts.get('stock:'+goal.itemId)??(owned[goal.itemId]||0))}"></label>${goal.status==='done'?'':`<button data-personal-toggle type="button">${esc(goal.status==='paused'?c().resume:c().pause)}</button>`}<button data-personal-remove type="button">${esc(c().remove)}</button></div>`).join(''):`<div class="planning-empty">${esc(c().noPersonal)}</div>`}
  function emptyMessage(){
    const hasPersonal=Object.values(window.RFTPlanning.personalGoals()).some(goal=>goal.status==='active');
    const activeQuests=typeof quests!=='undefined'?quests.filter(quest=>getQuestState(quest.id)==='active'):[];
    const hasWorkshop=typeof active!=='undefined'&&Object.values(active).some(Boolean);
    if(!hasPersonal&&!activeQuests.length&&!hasWorkshop)return x().none;
    if(!hasPersonal&&!hasWorkshop&&activeQuests.every(quest=>!(quest.requiredItemIds||[]).length))return x().tasks;
    return x().ready;
  }
  function render(){renderMissing();renderPersonal();syncLabels();let costs=document.getElementById('planningExtraCosts');if(!costs){costs=document.createElement('div');costs.id='planningExtraCosts';missing.after(costs)}costs.hidden=missing.hidden;const entries=typeof goals!=='undefined'?goals.flatMap(goal=>(goal.levels||[]).filter(level=>active[key(goal.id,level.level)]&&Array.isArray(level.other)&&level.other.length).map(level=>`${goalName(goal)} ${tr('level')} ${level.level}: ${level.other.join(' · ')}`)):[];costs.innerHTML=entries.length?`<div class="planning-empty">${entries.map(esc).join('<br>')}</div>`:''}

  root.addEventListener('input',event=>{const input=event.target,row=input.closest('[data-plan-item],[data-personal]');if(!row)return;const id=row.dataset.planItem||row.dataset.personal;if(input.matches('[data-find]'))drafts.set('find:'+id,input.value);if(input.matches('[data-stock],[data-personal-stock]'))drafts.set('stock:'+id,input.value)});
  missing.addEventListener('toggle',event=>{const row=event.target.closest('[data-plan-item]');if(row){if(event.target.open)openDetails.add(row.dataset.planItem);else openDetails.delete(row.dataset.planItem)}},true);
  document.getElementById('planningPersonalList').addEventListener('change',event=>{const row=event.target.closest('[data-personal]');if(row&&event.target.matches('[data-personal-stock]'))saveStock(row.dataset.personal,event.target.value)});

  function show(which){const isMissing=which==='missing';missing.hidden=!isMissing;goalsPane.hidden=isMissing;tabMissing.setAttribute('aria-selected',String(isMissing));tabGoals.setAttribute('aria-selected',String(!isMissing));window.RFTPlanningIntegratedSources?.setVisible(!isMissing);const costs=document.getElementById('planningExtraCosts');if(costs)costs.hidden=!isMissing}
  tabMissing.addEventListener('click',()=>show('missing'));tabGoals.addEventListener('click',()=>show('goals'));
  missing.addEventListener('change',e=>{const row=e.target.closest('[data-plan-item]');if(row&&e.target.matches('[data-stock]'))saveStock(row.dataset.planItem,e.target.value,false)});missing.addEventListener('click',e=>{const button=e.target.closest('[data-apply-find]');if(!button)return;const row=button.closest('[data-plan-item]'),input=row.querySelector('[data-find]');saveStock(row.dataset.planItem,input.value,true)});
  document.getElementById('planningPersonalAdd').addEventListener('click',()=>{const select=document.getElementById('planningPersonalItem'),amount=document.getElementById('planningPersonalAmount');if(!select.value)return;if(!amount.checkValidity()){amount.reportValidity();return}try{const goal=window.RFTPlanning.setPersonal(select.value,amount.value);status.textContent=goal.status==='done'?completedMessage([goal]):`${c().saved} ${goal.target} × ${name(goal.itemId)}.`;render()}catch{status.textContent=c().saveError}});
  document.getElementById('planningPersonalList').addEventListener('click',e=>{const row=e.target.closest('[data-personal]');if(!row||!e.target.closest('[data-personal-remove],[data-personal-toggle]'))return;const personal=window.RFTPlanning.personalGoals()[row.dataset.personal];try{if(e.target.closest('[data-personal-remove]'))window.RFTPlanning.removePersonal(row.dataset.personal);else if(e.target.closest('[data-personal-toggle]'))window.RFTPlanning.setPersonal(row.dataset.personal,personal.target,personal.status==='paused'?'active':'paused');render()}catch{status.textContent=c().saveError}});
  function populateItems(){const select=document.getElementById('planningPersonalItem');if(!select||typeof items==='undefined'||!Array.isArray(items)||!items.length)return;const current=select.value;select.innerHTML='<option value=""></option>'+items.filter(item=>name(item.id).toLocaleLowerCase().includes((document.getElementById('planningPersonalSearch')?.value||'').toLocaleLowerCase())).sort((a,b)=>name(a.id).localeCompare(name(b.id))).map(item=>`<option value="${esc(item.id)}">${esc(name(item.id))}</option>`).join('');select.value=current;select.options[0].textContent=select.options.length===1?x().noMatch:'—';syncLabels()}
  document.getElementById('planningPersonalSearch').addEventListener('input',populateItems);
  document.getElementById('planningPersonalItem').addEventListener('change',()=>{const goal=window.RFTPlanning.personalGoals()[document.getElementById('planningPersonalItem').value];if(goal)document.getElementById('planningPersonalAmount').value=goal.target;syncLabels()});
  function openItemGoal(id,button){
    const card=button.closest('.card');if(!card)return;let editor=card.querySelector('[data-goal-editor]');if(editor){editor.querySelector('input')?.focus();return}
    editor=document.createElement('div');editor.dataset.goalEditor='';editor.className='planning-search-goal';
    const goal=window.RFTPlanning.personalGoals()[id],label=document.createElement('label'),input=document.createElement('input'),save=document.createElement('button'),feedback=document.createElement('p'),link=document.createElement('a');
    label.textContent=(goal?`${x().existing}: ${goal.target}. `:'')+strings().amount;input.type='number';input.min='1';input.max='999999';input.step='1';input.inputMode='numeric';input.value=String(goal?.target||1);label.append(input);save.type='button';save.textContent=goal?x().change:c().add;feedback.setAttribute('role','status');link.href='#planningSection';link.textContent=x().open;link.hidden=true;
    save.addEventListener('click',()=>{if(!input.checkValidity()){input.reportValidity();return}try{const result=window.RFTPlanning.setPersonal(id,input.value);feedback.textContent=result.status==='done'?completedMessage([result]):`${c().saved} ${result.target} × ${name(id)}.`;link.hidden=false;save.textContent=x().change}catch{feedback.textContent=c().saveError}});
    editor.append(label,save,feedback,link);card.append(editor);input.focus();editor.scrollIntoView({block:'nearest'});
  }
  let catalogReference=null;setInterval(()=>{if(typeof items!=='undefined'&&Array.isArray(items)&&items.length&&items!==catalogReference){catalogReference=items;populateItems();render()}},500);
  window.RFTPlanningUI={syncLabels,openItemGoal,goalLabel,completedMessage};window.addEventListener('arc-language-change',()=>{populateItems();render();status.textContent=''});window.addEventListener('planning-changed',()=>{render();if(typeof drawSummary==='function')drawSummary();document.querySelectorAll('#out .card[data-item-id]').forEach(card=>{const current=card.querySelector('.need');if(current&&typeof goalDecision==='function'){const item=itemById(card.dataset.itemId);if(item)current.outerHTML=goalDecision(item)}})});window.addEventListener('raid-goals-completed',render);window.addEventListener('storage',render);document.addEventListener('click',event=>{if(root.contains(event.target))return;setTimeout(()=>{populateItems();render()},0)});setTimeout(()=>{populateItems();render()},600);show('missing');syncLabels();
})();
